name: build_sagit_hos_2.0
on:
  workflow_dispatch:
    inputs:
      STOCK_URL:
        description: "İşlenecek stok ROM/xiaomi.eu taban ROM indirme adresi"
        required: true
        default: 'https://cdnorg.d.miui.com/V14.0.8.0.TKKCNXM/miui_SAGIT_V14.0.8.0.TKKCNXM_example.zip'
      PORT_URL:
        description: https://netix.dl.sourceforge.net/project/xiaomi-eu-multilang-miui-roms/xiaomi.eu/HyperOS-STABLE-RELEASES/HyperOS2.0/xiaomi.eu_SUNSTONE_OS2.0.2.0.UMQCNXM_14.zip?viasf=1
        required: true
        
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Maksimum yapı ortamı
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: Depoyu kontrol et
        uses: actions/checkout@main
      - name: 1. Ortamı Hazırla
        run: |
          sudo apt install aria2 python3 busybox zip tar apktool unzip p7zip-full openjdk-8-jre zipalign zstd bc android-sdk-libsparse-utils
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          pip3 install pycryptodome requests setuptools docopt
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          unzip -P ${{ secrets.PASSWORD }} "$GITHUB_WORKSPACE"/tools/rclone.zip -d ~/.config/rclone/
      - name: 2. Depoyu Klonla
        run: |
          git clone --depth 1 https://github.com/lovezhen520/HyperOS_Action_builder hyperos_port
          aria2c -s 10 -x 10 -o devices.zip -d ./hyperos_port "${{ secrets.LINK }}"
          cd hyperos_port
          mkdir devices
          cd devices
          7z x ../devices.zip
          cd ..
          rm -rf devices.zip
      - name: 3. Portlama İşlemini Başlat
        run: |
          cd hyperos_port
          sudo bash port.sh "${{ github.event.inputs.STOCK_URL }}" "${{ github.event.inputs.PORT_URL }}" | tee HyperOS_portlog.log
      - name: 4. OneDrive'a Yükle
        run: |
            rclone mkdir onedrive:/Hyperos/sagit
            rclone sync -P ./hyperos_port/out/hyperos2.0_A14_Sagit.zip onedrive:/Hyperos/sagit
            cd ${{ github.workspace }}
            touch info.md
            echo "Gönderim Tarihi: $(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
            echo "Stok ROM Bağlantısı: ${{ github.event.inputs.STOCK_URL }}" >> info.md
            echo "Port ROM Bağlantısı: ${{ github.event.inputs.PORT_URL }}" >> info.md
            echo "HyperOS Sürümü: 2.0 (Android 14)" >> info.md
            
      - name: 5. Bu Çalışmanın Log Dosyasını Release'e Yükle
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "/home/runner/work/HyperOS_Action_builder/HyperOS_Action_builder/hyperos_port/HyperOS_portlog.log"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}
